#!/usr/bin/env sh

# To speed up the workshop this fakes the output
# for a real example of a security scanning image:
# - https://github.com/syntasso/kratix-marketplace/tree/main/pipeline-marketplace-images/snyk
# - https://github.com/syntasso/kratix-marketplace/tree/main/pipeline-marketplace-images/trivy

version=$(yq ".spec.version" /kratix/output/mongodb-instance.yaml)

vulns=0
message="no vulnerabilities found"
if [ "$version" = "4.4.23" ] || [ "$version" = "5.0.14" ]; then
    vulns=1
    message="MongoDB $version contains a critical vulnerability. Please update."
fi

echo """
Found follow images:
- docker.io/mongo:$version

Scanning images for vulnerabilities
...
...
...
$vulns vulnerabilities found
"""

echo "{vulnerabilities: \"$message\"}" > /kratix/metadata/status.yaml
