podTemplate(yaml: '''
              apiVersion: v1
              kind: Pod
              spec:
                serviceAccountName: knative-jenkins-deployer
                containers:
                - name: kubectl
                  image: bitnami/kubectl
                  imagePullPolicy: Always
                  command:
                  - sleep
                  args:
                  - 99d
                  securityContext:
                    runAsUser: 0
'''
  ) {

  node(POD_LABEL) {
    stage('Deploy application') {
      // secret manually added to the jenkins instance
      // this shouldnt be needed if the example app is a public repository
      git branch: 'main', credentialsId: 'github-access-token', url: 'git@github.com:syntasso/workshop.git'
      container('kubectl') {
        sh '''
        kubectl apply --filename ./sample-todo-app/k8s/serving.yaml
        until (( $(curl -s -o /dev/null -w "%{http_code}" -H "host: todo.default.example.com" kourier.kourier-system.svc.cluster.local) == 200 ))
        do
          sleep 2
        done
        '''
      }
    }
  }
}
