#!/usr/bin/env sh

set -e

name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"
namespace="$(yq eval '.spec.namespace // "default"' /kratix/input/object.yaml)"
export fullconfig="$(yq eval '.spec' /kratix/input/object.yaml)"

cat <<EOF | yq '.spec = env(fullconfig)' > /kratix/output/object.yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: $name
  namespace: $namespace
EOF